name: strict_json
description: The package allows you to work with dynamic data in a strict form.
version: 2.2.0
repository: https://github.com/siqwin/strict_json.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.0